### ISSUE TITLE
2MB Version

### ISSUE THREAD

**Issue by rmueller83** [SukkoPera/OpenKickstartSwitcher#1]
Hi,

could you also design a 2MB version? It would be nice to have a >2.0 Kickstart and additionally [DiagROM](http://www.diagrom.com/index.php/download/) which also needs 512KiB.

**Comment by SukkoPera** [comment]
Maybe one day, I still haven't had time to test the current version :(.

Anyway I think the 16bit version of DiagROM should fit in 256K, otherwise it wouldn't work on A500/2000's.

**Comment by SukkoPera** [comment]
Try this, it's DiagROM 1.0 16-bit version reduced to a 256Kb file. Needs to be byteswapped when burning to an actual EPROM.

Seems to work fine on UAE.

[diagrom-256k.zip](https://github.com/SukkoPera/OpenKickstartSwitcher/files/1777856/diagrom-256k.zip)

**Comment by SukkoPera** [comment]
Also tested on a couple of real Amigas, works well!

**Comment by SukkoPera** [comment]
V2, just released, exposes A19 when using a M27C160 EPROM and allows up to 6 Kickstarts: 4x256KB + 2x512KB. An additional switch will be needed, of course.

https://github.com/SukkoPera/OpenKickstartSwitcher/releases/tag/v2

**Comment by rmueller83** [comment]
Thank you, that's great news! I made 3 orders of M27C800 EPROMs (15 EPROMs in total) from China, but none of them works with the widespread MiniPro TL866 programmer and KeirF adaptor. :-( The M27C160 works fine with another switcher.

**Comment by SukkoPera** [comment]
That's weird, I use a TL866CS with ~~Keirf's~~ Gaggi's adapter and the M27C800s I ordered from China all work fine. Maybe they need to be erased first?

The same configuration also works with M27C160s.

**Comment by jingsno** [comment]
Thanks for designing the PCB, and making it available! Did you use any special tools to make the 256KB version of DiagROM, or just chop of the last 256KBs? Looks like your version has a few extra instructions right at the end of the 256KB address space, some jump instructions maybe? I'd like to flash the latest version of Diagrom, as it has some Zorro III fixes.

**Comment by SukkoPera** [comment]
Not really, I created it by hand. I guess I could come up with some Linux commands to make it, but I actually think that the 16-bit version of Diagrom should be a 256K file from the start.

Anyway, the version linked above is the latest one as far as I know, why do you think there's a later one? Do you mean the daily build?

**Comment by SukkoPera** [comment]
I have been examinating the latest daily release and I think you can just truncate the ROM at 256k.

I also saw it has a new checksum feature, which will fail, but the ROM should work well anyway, as there's nothing in the part that gets truncated. Actually, at offset 0x21C80 (which comes way before the truncation point), the ROM contains the following message:

    This is the brutal end of this ROM, everything after this are just pure noise.    End of Code
