### ISSUE TITLE
Switcher don´t fit between Mainboard and Keyboard

### ISSUE THREAD

**Issue by Konstantin19** [SukkoPera/OpenKickstartSwitcher#2]
There is not enough space between mainboard and keyboard. You have to make an offset of the eprom with at least 5 pins to the back. But there is a capacitor so that this is not a good idea. Whats about to put a 40 pin (2x20) header to use an IDE HDD flat cable in combination with a IC socket connector?

Tested on Amiga 500 Rev.8a.1

Technically working 100% with Kick 1.3 / Kick 3.1 / Diag ROM

![k1600_wp_20180517_19_13_05_pro](https://user-images.githubusercontent.com/16501506/40381272-8dc6e726-5dfb-11e8-8d19-3a94189ba9bb.JPG)

![download](https://user-images.githubusercontent.com/16501506/40381584-58b4732c-5dfc-11e8-8183-f728c3df583c.jpg)

**Comment by SukkoPera** [comment]
That issue has already been taken care of in V2. I received the prototypes last Saturday and tested them yesterday, the situation improves a lot.

I had added some information to the V1 release saying that the board wouldn't fit as soon as I had tested it, which is a few months ago, but I guess you missed that :(.

I will release V2 ASAP.

![OKS](https://www.dropbox.com/s/jv2uiiooumskxhr/Foto%2019-05-18%2C%2018%2028%2018.jpg?dl=0&raw=1)
(Ignore green wire)

**Comment by SukkoPera** [comment]
https://www.dropbox.com/s/jv2uiiooumskxhr/Foto%2019-05-18%2C%2018%2028%2018.jpg?dl=0&raw=1

**Comment by Kalidomra** [comment]
Any ETA on V2?

**Comment by SukkoPera** [comment]
Tests completed this morning. It's now released:

https://github.com/SukkoPera/OpenKickstartSwitcher/releases/tag/v2

The link to buy PCBs to support the project will probably go live in a few hours.
